// packages/ui/src/components/controls/breadcrumb/Breadcrumb.vue
<template>
  <el-breadcrumb :separator="separator" class="custom-breadcrumb" :style="containerStyle">
    <el-breadcrumb-item v-for="(item, index) in displayItems" :key="index">
      <span v-if="index === displayItems.length - 1" class="current">{{ item.label }}</span>
      <a v-else class="link" @click="handleItemClick(item)">{{ item.label }}</a>
    </el-breadcrumb-item>
  </el-breadcrumb>
</template>

<script setup lang="ts">
import { computed } from 'vue'
import type { CSSProperties } from 'vue'
import { ElBreadcrumb, ElBreadcrumbItem } from 'element-plus'

export interface BreadcrumbItem {
  label: string
  pageId?: string
  url?: string
}

export interface BreadcrumbProps {
  items?: BreadcrumbItem[]
  separator?: string
  fontSize?: number
  color?: string
  activeColor?: string
  linkColor?: string
}

const props = withDefaults(defineProps<BreadcrumbProps>(), {
  items: () => [],
  separator: '/',
  fontSize: 14,
  color: '#606266',
  activeColor: '#909399',
  linkColor: '#409eff',
})

const emit = defineEmits<{
  itemClick: [item: BreadcrumbItem]
}>()

// 默认显示项
const defaultItems: BreadcrumbItem[] = [{ label: '首页', pageId: 'home' }, { label: '当前页面' }]

const displayItems = computed(() => {
  return props.items.length > 0 ? props.items : defaultItems
})

const containerStyle = computed<CSSProperties>(() => ({
  fontSize: `${props.fontSize}px`,
  '--breadcrumb-color': props.color,
  '--breadcrumb-active-color': props.activeColor,
  '--breadcrumb-link-color': props.linkColor,
}))

function handleItemClick(item: BreadcrumbItem) {
  emit('itemClick', item)
}
</script>

<style scoped>
.custom-breadcrumb {
  padding: 8px 16px;
}

.link {
  cursor: pointer;
  color: var(--breadcrumb-link-color, #409eff);
}

.link:hover {
  text-decoration: underline;
}

.current {
  color: var(--breadcrumb-active-color, #909399);
}
</style>

// packages/ui-react/src/components/Breadcrumb.tsx
import React, { forwardRef } from 'react'

export interface BreadcrumbItem {
  label: string
  pageId?: string
  url?: string
}

export interface BreadcrumbProps extends React.HTMLAttributes<HTMLElement> {
  /** 面包屑项列表 */
  items?: BreadcrumbItem[]
  /** 分隔符 */
  separator?: string
  /** 字号 */
  fontSize?: number
  /** 文字颜色 */
  color?: string
  /** 当前项颜色 */
  activeColor?: string
  /** 链接颜色 */
  linkColor?: string
  /** 点击项回调 */
  onItemClick?: (item: BreadcrumbItem) => void
}

const defaultItems: BreadcrumbItem[] = [{ label: '首页', pageId: 'home' }, { label: '当前页面' }]

export const Breadcrumb = forwardRef<HTMLElement, BreadcrumbProps>(
  (
    {
      items,
      separator = '/',
      fontSize = 14,
      color = '#606266',
      activeColor = '#909399',
      linkColor = '#409eff',
      onItemClick,
      style,
      ...rest
    },
    ref,
  ) => {
    const displayItems = items && items.length > 0 ? items : defaultItems

    const containerStyle: React.CSSProperties = {
      display: 'flex',
      alignItems: 'center',
      flexWrap: 'wrap',
      gap: '4px',
      padding: '8px 16px',
      fontSize: `${fontSize}px`,
      color,
      ...style,
    }

    return (
      <nav ref={ref} style={containerStyle} aria-label="breadcrumb" {...rest}>
        {displayItems.map((item, index) => {
          const isLast = index === displayItems.length - 1

          return (
            <React.Fragment key={index}>
              {isLast ? (
                <span style={{ color: activeColor }}>{item.label}</span>
              ) : (
                <a
                  style={{
                    color: linkColor,
                    cursor: 'pointer',
                    textDecoration: 'none',
                  }}
                  onClick={() => onItemClick?.(item)}
                  onMouseEnter={(e) => {
                    ;(e.target as HTMLAnchorElement).style.textDecoration = 'underline'
                  }}
                  onMouseLeave={(e) => {
                    ;(e.target as HTMLAnchorElement).style.textDecoration = 'none'
                  }}
                >
                  {item.label}
                </a>
              )}
              {!isLast && <span style={{ color, margin: '0 4px' }}>{separator}</span>}
            </React.Fragment>
          )
        })}
      </nav>
    )
  },
)

Breadcrumb.displayName = 'Breadcrumb'
