// packages/ui/src/components/layout/grid/Grid.vue
<template>
  <div class="v-grid-container" :style="containerStyle">
    <slot>
      <template v-if="placeholderItems.length">
        <div v-for="(item, idx) in placeholderItems" :key="idx" class="v-grid-placeholder-item">
          {{ item }}
        </div>
      </template>
    </slot>
  </div>
</template>

<script setup lang="ts">
import { computed } from 'vue'
import type { CSSProperties } from 'vue'

// 定义纯 UI Props
const props = withDefaults(
  defineProps<{
    // Grid 布局属性
    columns?: number | string
    rows?: number | string
    gap?: number | string
    rowGap?: number | string
    columnGap?: number | string
    autoFlow?: 'row' | 'column' | 'dense' | 'row dense' | 'column dense'

    // 容器样式
    padding?: number | string
    backgroundColor?: string
    borderRadius?: number | string
    minHeight?: number | string

    // 占位内容
    content?: string
    placeholderItems?: string[]
  }>(),
  {
    columns: 'repeat(3, 1fr)',
    rows: 'auto',
    gap: '16px',
    rowGap: '',
    columnGap: '',
    autoFlow: 'row',
    padding: '16px',
    backgroundColor: '#ffffff',
    borderRadius: '4px',
    minHeight: '200px',
    placeholderItems: () => ['Grid 1', 'Grid 2', 'Grid 3'],
  },
)

function toCssLength(value: number | string | undefined, fallback = ''): string {
  if (value === undefined || value === null || value === '') {
    return fallback
  }
  if (typeof value === 'number') {
    return `${value}px`
  }
  return value
}

function toTemplate(value: number | string | undefined, fallback: string): string {
  if (value === undefined || value === null || value === '') {
    return fallback
  }
  if (typeof value === 'number') {
    return `repeat(${Math.max(1, Math.round(value))}, 1fr)`
  }
  return value
}

// 容器样式
const containerStyle = computed<CSSProperties>(() => {
  return {
    display: 'grid',
    gridTemplateColumns: toTemplate(props.columns, 'repeat(3, 1fr)'),
    gridTemplateRows: toTemplate(props.rows, 'auto'),
    gap: toCssLength(props.gap, '16px'),
    rowGap: toCssLength(props.rowGap),
    columnGap: toCssLength(props.columnGap),
    gridAutoFlow: props.autoFlow,
    padding: toCssLength(props.padding, '16px'),
    backgroundColor: props.backgroundColor,
    borderRadius: toCssLength(props.borderRadius, '4px'),
    minHeight: toCssLength(props.minHeight, '200px'),
    boxSizing: 'border-box',
  }
})

// 占位项
const placeholderItems = computed(() => {
  return props.placeholderItems
})
</script>

<style scoped>
.v-grid-container {
  box-sizing: border-box;
  width: 100%;
}

.v-grid-placeholder-item {
  padding: 12px;
  background-color: #f3f4f6;
  border-radius: 4px;
  text-align: center;
}
</style>

// packages/ui-react/src/components/Grid.tsx
import React, { forwardRef } from 'react'

export interface GridProps extends React.HTMLAttributes<HTMLDivElement> {
  columns?: number | string
  rows?: number | string
  gap?: number | string
  rowGap?: number | string
  columnGap?: number | string
  autoFlow?: 'row' | 'column' | 'dense' | 'row dense' | 'column dense'
  alignItems?: 'start' | 'end' | 'center' | 'stretch'
  justifyItems?: 'start' | 'end' | 'center' | 'stretch'
  padding?: number | string
  backgroundColor?: string
  borderRadius?: number | string
  minHeight?: number | string
}

export const Grid = forwardRef<HTMLDivElement, GridProps>(
  (
    {
      columns,
      rows,
      gap,
      rowGap,
      columnGap,
      autoFlow,
      alignItems,
      justifyItems,
      padding,
      backgroundColor,
      borderRadius,
      minHeight,
      style,
      children,
      ...props
    },
    ref,
  ) => {
    const combinedStyle: React.CSSProperties = {
      display: 'grid',
      gridTemplateColumns: typeof columns === 'number' ? `repeat(${columns}, 1fr)` : columns,
      gridTemplateRows: typeof rows === 'number' ? `repeat(${rows}, 1fr)` : rows,
      gap: typeof gap === 'number' ? `${gap}px` : gap,
      rowGap: typeof rowGap === 'number' ? `${rowGap}px` : rowGap,
      columnGap: typeof columnGap === 'number' ? `${columnGap}px` : columnGap,
      gridAutoFlow: autoFlow,
      alignItems,
      justifyItems,
      padding: typeof padding === 'number' ? `${padding}px` : padding,
      backgroundColor,
      borderRadius: typeof borderRadius === 'number' ? `${borderRadius}px` : borderRadius,
      minHeight: typeof minHeight === 'number' ? `${minHeight}px` : minHeight,
      ...style,
    }

    return (
      <div ref={ref} style={combinedStyle} {...props}>
        {children}
      </div>
    )
  },
)

Grid.displayName = 'Grid'
