// packages/ui/src/components/controls/textareaInput/TextareaInput.vue
<template>
  <div class="textarea-input-container" :style="containerStyle">
    <el-input
      v-model="internalValue"
      type="textarea"
      :placeholder="placeholder"
      :disabled="disabled"
      :size="size"
      :rows="rows"
      :autosize="autosize"
      :maxlength="maxlength"
      :show-word-limit="showWordLimit"
      :resize="resize"
      :style="inputStyle"
      @input="handleInput"
      @change="handleChange"
    />
  </div>
</template>

<script setup lang="ts">
import { computed, ref, watch } from 'vue'
import type { CSSProperties } from 'vue'
import { ElInput } from 'element-plus'

type AutoSize = boolean | { minRows?: number; maxRows?: number }

const props = withDefaults(
  defineProps<{
    modelValue?: string
    defaultValue?: string
    placeholder?: string
    disabled?: boolean
    size?: 'large' | 'default' | 'small'
    rows?: number
    autosize?: AutoSize
    maxlength?: number
    showWordLimit?: boolean
    resize?: 'none' | 'both' | 'horizontal' | 'vertical'
    padding?: number
    backgroundColor?: string
    borderRadius?: number
    opacity?: number
    inputWidth?: number
  }>(),
  {
    modelValue: '',
    defaultValue: '',
    placeholder: '请输入',
    disabled: false,
    size: 'default',
    rows: 4,
    autosize: false,
    maxlength: undefined,
    showWordLimit: false,
    resize: 'vertical',
    padding: 8,
    backgroundColor: 'transparent',
    borderRadius: 4,
    opacity: 100,
    inputWidth: 100,
  },
)

const emit = defineEmits<{
  'update:modelValue': [value: string]
  input: [value: string]
  change: [value: string]
}>()

const internalValue = ref(props.modelValue || props.defaultValue || '')

watch(
  () => [props.modelValue, props.defaultValue],
  ([modelValue, defaultValue]) => {
    internalValue.value = modelValue ?? defaultValue ?? ''
  },
)

const containerStyle = computed<CSSProperties>(() => ({
  opacity: props.opacity / 100,
  display: 'flex',
  alignItems: 'stretch',
  width: '100%',
  height: '100%',
  padding: `${props.padding}px`,
  backgroundColor: props.backgroundColor,
  borderRadius: `${props.borderRadius}px`,
  boxSizing: 'border-box',
}))

const inputStyle = computed<CSSProperties>(() => ({
  width: `${props.inputWidth}%`,
}))

function handleInput(value: string) {
  emit('update:modelValue', value)
  emit('input', value)
}

function handleChange(value: string) {
  emit('change', value)
}
</script>

<style scoped>
.textarea-input-container {
  box-sizing: border-box;
}
</style>

// packages/ui-react/src/components/TextareaInput.tsx
import React, { forwardRef, useState } from 'react'

type AutoSize = boolean | { minRows?: number; maxRows?: number }

export interface TextareaInputProps
  extends Omit<React.HTMLAttributes<HTMLDivElement>, 'onChange' | 'defaultValue'> {
  value?: string
  defaultValue?: string
  onChange?: (value: string) => void
  placeholder?: string
  disabled?: boolean
  size?: 'small' | 'default' | 'medium' | 'large'
  rows?: number
  autosize?: AutoSize
  maxlength?: number
  showWordLimit?: boolean
  resize?: 'none' | 'both' | 'horizontal' | 'vertical'
}

export const TextareaInput = forwardRef<HTMLDivElement, TextareaInputProps>(
  (
    {
      value: controlledValue,
      defaultValue = '',
      onChange,
      placeholder = 'Please input',
      disabled = false,
      size = 'medium',
      rows = 4,
      autosize = false,
      maxlength,
      showWordLimit = false,
      resize = 'vertical',
      style,
      ...props
    },
    ref,
  ) => {
    const [internalValue, setInternalValue] = useState(defaultValue)
    const value = controlledValue ?? internalValue

    const sizeMap = {
      small: { fontSize: '12px', padding: '6px 8px' },
      default: { fontSize: '14px', padding: '8px 10px' },
      medium: { fontSize: '14px', padding: '10px 12px' },
      large: { fontSize: '16px', padding: '12px 14px' },
    }

    const sizePreset = sizeMap[size]
    const minRows = typeof autosize === 'object' ? autosize.minRows : undefined
    const maxRows = typeof autosize === 'object' ? autosize.maxRows : undefined
    const effectiveRows = minRows ?? rows

    const handleChange = (nextValue: string) => {
      if (controlledValue === undefined) {
        setInternalValue(nextValue)
      }
      onChange?.(nextValue)
    }

    return (
      <div
        ref={ref}
        style={{
          display: 'inline-flex',
          flexDirection: 'column',
          width: '100%',
          gap: '4px',
          ...style,
        }}
        {...props}
      >
        <textarea
          value={value}
          rows={effectiveRows}
          placeholder={placeholder}
          disabled={disabled}
          maxLength={maxlength}
          onChange={(e) => handleChange(e.target.value)}
          style={{
            width: '100%',
            border: '1px solid #d9d9d9',
            borderRadius: '4px',
            fontSize: sizePreset.fontSize,
            padding: sizePreset.padding,
            resize,
            outline: 'none',
            backgroundColor: disabled ? '#f5f5f5' : '#fff',
            opacity: disabled ? 0.6 : 1,
            minHeight: typeof autosize === 'boolean' && autosize ? `${rows * 24}px` : undefined,
            maxHeight: typeof maxRows === 'number' ? `${maxRows * 24}px` : undefined,
            boxSizing: 'border-box',
          }}
        />
        {showWordLimit && typeof maxlength === 'number' && (
          <span style={{ color: '#999', fontSize: '12px', textAlign: 'right' }}>
            {value.length}/{maxlength}
          </span>
        )}
      </div>
    )
  },
)

TextareaInput.displayName = 'TextareaInput'
