// packages/ui-react/src/components/RadioGroup.tsx
import React, { forwardRef, useState } from 'react'

export interface RadioOption {
  label: React.ReactNode
  value: string | number | boolean
  disabled?: boolean
}

export interface RadioGroupProps
  extends Omit<React.HTMLAttributes<HTMLDivElement>, 'onChange' | 'defaultValue'> {
  value?: string | number | boolean
  defaultValue?: string | number | boolean
  options?: RadioOption[]
  onChange?: (value: string | number | boolean) => void
  disabled?: boolean
  size?: 'small' | 'default' | 'medium' | 'large'
  direction?: 'horizontal' | 'vertical'
  optionType?: 'default' | 'button'
  gap?: number
}

export const RadioGroup = forwardRef<HTMLDivElement, RadioGroupProps>(
  (
    {
      value: controlledValue,
      defaultValue,
      options = [],
      onChange,
      disabled = false,
      size = 'medium',
      direction = 'horizontal',
      optionType = 'default',
      gap = 12,
      style,
      ...props
    },
    ref,
  ) => {
    const [internalValue, setInternalValue] = useState<string | number | boolean | undefined>(
      defaultValue,
    )
    const value = controlledValue ?? internalValue

    const sizeMap = {
      small: { fontSize: '12px', padding: '4px 8px' },
      default: { fontSize: '14px', padding: '5px 10px' },
      medium: { fontSize: '14px', padding: '6px 12px' },
      large: { fontSize: '16px', padding: '8px 14px' },
    }
    const sizePreset = sizeMap[size]

    const resolvedOptions = options.length
      ? options
      : [
          { label: 'Option A', value: 'a' },
          { label: 'Option B', value: 'b' },
        ]

    const handleChange = (nextValue: string | number | boolean, optionDisabled?: boolean) => {
      if (disabled || optionDisabled) {
        return
      }
      if (controlledValue === undefined) {
        setInternalValue(nextValue)
      }
      onChange?.(nextValue)
    }

    return (
      <div
        ref={ref}
        style={{
          display: 'inline-flex',
          flexDirection: direction === 'vertical' ? 'column' : 'row',
          gap: `${gap}px`,
          ...style,
        }}
        {...props}
      >
        {resolvedOptions.map((option) => {
          const checked = option.value === value
          const optionDisabled = disabled || option.disabled

          if (optionType === 'button') {
            return (
              <button
                key={String(option.value)}
                type="button"
                disabled={optionDisabled}
                onClick={() => handleChange(option.value, option.disabled)}
                style={{
                  border: `1px solid ${checked ? '#1890ff' : '#d9d9d9'}`,
                  backgroundColor: checked ? '#e6f7ff' : '#fff',
                  color: checked ? '#1890ff' : '#333',
                  borderRadius: '4px',
                  cursor: optionDisabled ? 'not-allowed' : 'pointer',
                  opacity: optionDisabled ? 0.6 : 1,
                  padding: sizePreset.padding,
                  fontSize: sizePreset.fontSize,
                }}
              >
                {option.label}
              </button>
            )
          }

          return (
            <label
              key={String(option.value)}
              style={{
                display: 'inline-flex',
                alignItems: 'center',
                gap: '8px',
                cursor: optionDisabled ? 'not-allowed' : 'pointer',
                opacity: optionDisabled ? 0.6 : 1,
                fontSize: sizePreset.fontSize,
              }}
            >
              <input
                type="radio"
                checked={checked}
                disabled={optionDisabled}
                onChange={() => handleChange(option.value, option.disabled)}
                style={{ margin: 0 }}
              />
              <span>{option.label}</span>
            </label>
          )
        })}
      </div>
    )
  },
)

RadioGroup.displayName = 'RadioGroup'

// packages/ui/src/components/controls/radioGroup/RadioGroup.vue
<template>
  <div class="radio-group-container" :style="containerStyle">
    <el-radio-group
      v-model="internalValue"
      :size="size"
      :disabled="disabled"
      :style="groupStyle"
      @change="handleChange"
    >
      <component
        :is="optionType === 'button' ? 'el-radio-button' : 'el-radio'"
        v-for="option in displayOptions"
        :key="String(option.value)"
        :label="option.value"
        :disabled="option.disabled"
      >
        {{ option.label }}
      </component>
    </el-radio-group>
  </div>
</template>

<script setup lang="ts">
import { computed, ref, watch } from 'vue'
import type { CSSProperties } from 'vue'
import { ElRadioGroup } from 'element-plus'

interface RadioOption {
  label: string
  value: string | number | boolean
  disabled?: boolean
}

const props = withDefaults(
  defineProps<{
    modelValue?: string | number | boolean
    defaultValue?: string | number | boolean
    options?: RadioOption[]
    disabled?: boolean
    size?: 'large' | 'default' | 'small'
    direction?: 'horizontal' | 'vertical'
    gap?: number
    optionType?: 'default' | 'button'
    padding?: number
    backgroundColor?: string
  }>(),
  {
    modelValue: undefined,
    defaultValue: undefined,
    options: () => [],
    disabled: false,
    size: 'default',
    direction: 'horizontal',
    gap: 12,
    optionType: 'default',
    padding: 8,
    backgroundColor: 'transparent',
  },
)

const emit = defineEmits<{
  'update:modelValue': [value: string | number | boolean | undefined]
  change: [value: string | number | boolean | undefined]
}>()

const defaultOptions: RadioOption[] = [
  { label: '选项 A', value: 'a' },
  { label: '选项 B', value: 'b' },
]

const displayOptions = computed(() => (props.options.length > 0 ? props.options : defaultOptions))

const internalValue = ref<string | number | boolean | undefined>(
  props.modelValue ?? props.defaultValue,
)

watch(
  () => [props.modelValue, props.defaultValue],
  ([modelValue, defaultValue]) => {
    internalValue.value = modelValue ?? defaultValue
  },
)

const containerStyle = computed<CSSProperties>(() => ({
  display: 'flex',
  alignItems: 'center',
  width: '100%',
  height: '100%',
  padding: `${props.padding}px`,
  backgroundColor: props.backgroundColor,
  boxSizing: 'border-box',
}))

const groupStyle = computed<CSSProperties>(() => ({
  display: 'flex',
  flexDirection: props.direction === 'vertical' ? 'column' : 'row',
  gap: `${props.gap}px`,
}))

function handleChange(value: string | number | boolean | undefined) {
  emit('update:modelValue', value)
  emit('change', value)
}
</script>

<style scoped>
.radio-group-container {
  box-sizing: border-box;
}
</style>
