// packages/ui-react/src/components/TextInput.tsx
import React, { forwardRef, useState } from 'react'

export interface TextInputProps
  extends Omit<React.HTMLAttributes<HTMLDivElement>, 'onChange' | 'defaultValue'> {
  value?: string
  defaultValue?: string
  onChange?: (value: string) => void
  placeholder?: string
  disabled?: boolean
  clearable?: boolean
  type?: 'text' | 'password' | 'email' | 'tel' | 'url'
  size?: 'small' | 'default' | 'medium' | 'large'
  maxlength?: number
  showWordLimit?: boolean
}

export const TextInput = forwardRef<HTMLDivElement, TextInputProps>(
  (
    {
      value: controlledValue,
      defaultValue = '',
      onChange,
      placeholder = 'Please input',
      disabled = false,
      clearable = true,
      type = 'text',
      size = 'medium',
      maxlength,
      showWordLimit = false,
      style,
      ...props
    },
    ref,
  ) => {
    const [internalValue, setInternalValue] = useState(defaultValue)
    const value = controlledValue ?? internalValue

    const sizeMap = {
      small: { height: '28px', fontSize: '12px', padding: '0 8px' },
      default: { height: '32px', fontSize: '14px', padding: '0 10px' },
      medium: { height: '36px', fontSize: '14px', padding: '0 12px' },
      large: { height: '44px', fontSize: '16px', padding: '0 14px' },
    }

    const sizePreset = sizeMap[size]

    const handleChange = (nextValue: string) => {
      if (controlledValue === undefined) {
        setInternalValue(nextValue)
      }
      onChange?.(nextValue)
    }

    const handleClear = () => handleChange('')

    return (
      <div
        ref={ref}
        style={{
          display: 'inline-flex',
          flexDirection: 'column',
          width: '100%',
          gap: '4px',
          ...style,
        }}
        {...props}
      >
        <div
          style={{
            display: 'flex',
            alignItems: 'center',
            height: sizePreset.height,
            padding: sizePreset.padding,
            border: '1px solid #d9d9d9',
            borderRadius: '4px',
            backgroundColor: disabled ? '#f5f5f5' : '#fff',
            opacity: disabled ? 0.6 : 1,
          }}
        >
          <input
            type={type}
            value={value}
            placeholder={placeholder}
            disabled={disabled}
            maxLength={maxlength}
            onChange={(e) => handleChange(e.target.value)}
            style={{
              flex: 1,
              border: 'none',
              outline: 'none',
              fontSize: sizePreset.fontSize,
              backgroundColor: 'transparent',
              minWidth: 0,
            }}
          />
          {clearable && value && !disabled && (
            <button
              type="button"
              onClick={handleClear}
              style={{
                border: 'none',
                background: 'transparent',
                color: '#999',
                cursor: 'pointer',
                padding: 0,
                marginLeft: '6px',
                fontSize: '12px',
                lineHeight: 1,
              }}
            >
              ×
            </button>
          )}
        </div>
        {showWordLimit && typeof maxlength === 'number' && (
          <span style={{ color: '#999', fontSize: '12px', textAlign: 'right' }}>
            {value.length}/{maxlength}
          </span>
        )}
      </div>
    )
  },
)

TextInput.displayName = 'TextInput'

// packages/ui/src/components/controls/textInput/TextInput.vue
<template>
  <div class="text-input-container" :style="containerStyle">
    <el-input
      v-model="internalValue"
      :type="type"
      :placeholder="placeholder"
      :clearable="clearable"
      :disabled="disabled"
      :size="size"
      :maxlength="maxlength"
      :show-word-limit="showWordLimit"
      :style="inputStyle"
      @input="handleInput"
      @change="handleChange"
    />
  </div>
</template>

<script setup lang="ts">
import { computed, ref, watch } from 'vue'
import type { CSSProperties } from 'vue'
import { ElInput } from 'element-plus'

const props = withDefaults(
  defineProps<{
    modelValue?: string
    defaultValue?: string
    type?: 'text' | 'password' | 'email' | 'tel' | 'url'
    placeholder?: string
    clearable?: boolean
    disabled?: boolean
    size?: 'large' | 'default' | 'small'
    maxlength?: number
    showWordLimit?: boolean
    padding?: number
    backgroundColor?: string
    borderRadius?: number
    opacity?: number
    inputWidth?: number
  }>(),
  {
    modelValue: '',
    defaultValue: '',
    type: 'text',
    placeholder: '请输入',
    clearable: true,
    disabled: false,
    size: 'default',
    maxlength: undefined,
    showWordLimit: false,
    padding: 8,
    backgroundColor: 'transparent',
    borderRadius: 4,
    opacity: 100,
    inputWidth: 100,
  },
)

const emit = defineEmits<{
  'update:modelValue': [value: string]
  input: [value: string]
  change: [value: string]
}>()

const internalValue = ref(props.modelValue || props.defaultValue || '')

watch(
  () => [props.modelValue, props.defaultValue],
  ([modelValue, defaultValue]) => {
    internalValue.value = modelValue ?? defaultValue ?? ''
  },
)

const containerStyle = computed<CSSProperties>(() => ({
  opacity: props.opacity / 100,
  display: 'flex',
  alignItems: 'center',
  width: '100%',
  height: '100%',
  padding: `${props.padding}px`,
  backgroundColor: props.backgroundColor,
  borderRadius: `${props.borderRadius}px`,
  boxSizing: 'border-box',
}))

const inputStyle = computed<CSSProperties>(() => ({
  width: `${props.inputWidth}%`,
}))

function handleInput(value: string) {
  emit('update:modelValue', value)
  emit('input', value)
}

function handleChange(value: string) {
  emit('change', value)
}
</script>

<style scoped>
.text-input-container {
  box-sizing: border-box;
}
</style>
